package com.everyWear.everyWear.model;
// Generated Mar 27, 2026, 6:53:32 PM by Hibernate Tools 5.5.9.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Date createdAt;
	private Set items = new HashSet(0);
	private Set promotionCategories = new HashSet(0);

	public Category() {
	}

	public Category(String name, Date createdAt) {
		this.name = name;
		this.createdAt = createdAt;
	}

	public Category(String name, String description, Date createdAt, Set items, Set promotionCategories) {
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.items = items;
		this.promotionCategories = promotionCategories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

	public Set getPromotionCategories() {
		return this.promotionCategories;
	}

	public void setPromotionCategories(Set promotionCategories) {
		this.promotionCategories = promotionCategories;
	}

}
