package com.everyWear.everyWear.model;
// Generated Mar 27, 2026, 6:53:32 PM by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String description;
	private BigDecimal price;
	private boolean isActive;
	private Date createdAt;
	private Date updatedAt;
	private Set orderDetails = new HashSet(0);
	private Set stocks = new HashSet(0);

	public Item() {
	}

	public Item(String name, BigDecimal price, boolean isActive, Date createdAt, Date updatedAt) {
		this.name = name;
		this.price = price;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Item(Category category, String name, String description, BigDecimal price, boolean isActive, Date createdAt,
			Date updatedAt, Set orderDetails, Set stocks) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.price = price;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderDetails = orderDetails;
		this.stocks = stocks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
