package com.everyWear.everyWear.model;
// Generated Mar 27, 2026, 6:53:32 PM by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer id;
	private Coupon coupon;
	private Date orderDate;
	private BigDecimal discountAmount;
	private BigDecimal totalPrice;
	private BigDecimal netValue;
	private Date createdAt;
	private Set orderDetails = new HashSet(0);

	public Orders() {
	}

	public Orders(Date orderDate, BigDecimal totalPrice, BigDecimal netValue, Date createdAt) {
		this.orderDate = orderDate;
		this.totalPrice = totalPrice;
		this.netValue = netValue;
		this.createdAt = createdAt;
	}

	public Orders(Coupon coupon, Date orderDate, BigDecimal discountAmount, BigDecimal totalPrice, BigDecimal netValue,
			Date createdAt, Set orderDetails) {
		this.coupon = coupon;
		this.orderDate = orderDate;
		this.discountAmount = discountAmount;
		this.totalPrice = totalPrice;
		this.netValue = netValue;
		this.createdAt = createdAt;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	public BigDecimal getNetValue() {
		return this.netValue;
	}

	public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
