package com.everyWear.everyWear.model;
// Generated Mar 27, 2026, 6:53:32 PM by Hibernate Tools 5.5.9.Final

/**
 * PromotionCategory generated by hbm2java
 */
public class PromotionCategory implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Promotion promotion;

	public PromotionCategory() {
	}

	public PromotionCategory(Category category, Promotion promotion) {
		this.category = category;
		this.promotion = promotion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

}
