package com.everyWear.everyWear.model;
// Generated Mar 27, 2026, 6:53:32 PM by Hibernate Tools 5.5.9.Final


import java.util.Date;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private String size;
     private int quantity;
     private Date updatedAt;

    public Stock() {
    }

    public Stock(Item item, String size, int quantity, Date updatedAt) {
       this.item = item;
       this.size = size;
       this.quantity = quantity;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


