server:
  port: 8080

spring:
  application:    
    name: everyWear
  datasource:
    url: {DB_URL}
    username: {DB_USER}
    password: {DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 2. บังคับใส่ Dialect ไปเลยเพื่อป้องกัน Spring Boot เดาผิด
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true